# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f9c7b537b0272e5c44190590b1edd9ce1cf1106a9a6c116799ae98f26044d218cf0cf6426907909b1e912fe529caef3b915aa3dff96948103dd359757faa5f

test:
  secret_key_base: 0be0cb164a47afa5b2d28be9639a2fb9b581788f777942f2442e4cda97a87b3807a2c71ccbf0ffbabed29fd3c173201fa7ee60db3c31487af7bdf23460142bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
